# Generated by Django 3.2.12 on 2022-09-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_alter_talent_uploads_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent_uploads',
            name='desc',
            field=models.CharField(max_length=501),
        ),
    ]
